### ISSUE TITLE
Add structured data support to the "Team" post type

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/to-team#2]
[TO Demo](https://to-demo.lsdev.biz/team/ashley-shaw/)
[Google Structured Tool](https://search.google.com/structured-data/testing-tool/u/0/?utm_campaign=devsite&utm_medium=jsonld&utm_source=review-snippet#url=https%3A%2F%2Fto-demo.lsdev.biz%2Fteam%2Fashley-shaw%2F)
[Person Schema](https://schema.org/Person)

**Comment by krugazul** [comment]
@ashleyshaw I have gone through the [Person](https://schema.org/Person) schema, and Ive connected the fields that have relevant parameters.

Complete
 - `jobTitle` ( the role taxonomy)
 - `worksFor` (Yoast Organization Fields)
 - `memberOf` (Yoast Organization Fields)
 - `email` (custom field)
 - `telephone` (custom field)
 - `owns` (connected, tours and accommodation this member manages)
 - `makesOffer` (connected specials, you would contact this team member in order to organise the special)

WontDo
 - `givenName`, `familyName`, `honorificSuffix`, `honorificPrefix` ( we use the post title as `name`, which would contain these field values, so we can leave them out.)
 - `contactPoint` (we have the telephone number field )
 - `homeLocation` (no field for this)
 - `nationality` (no field for this)
 - `additionalName` (no field for this)

Reviews - do not connect to person, only an organisation.
Posts - There currently isnt a parameter I can connect posts authored by this team member.
Destinations - On tour operator sites, a person manages a destination, it is not where they are located (home country).  And currently there is no parameter to handle managed destinations.
